version: '3.7'

services:
  postgres_uniticket:
    image: postgres:11
    container_name: postgres_uniticket
    hostname: uniticket_db
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - 5432:5432

  postgres_test_uniticket:
    image: postgres:11
    container_name: postgres_test_uniticket
    hostname: uniticket_test_db
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - 5433:5432

  redis_uniticket:
    image: redis
    container_name: redis_uniticket
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
